################################################################
#*-- AUTHOR : Hector Alvarez-Pol
#*-- Date: 05/2005
#*-- Last Update: 15/05/08
#*-- Copyright: GENP (Univ. Santiago de Compostela)
# --------------------------------------------------------------
# Comments:
#     - 15/05/08 Multidetector geometry
#     - 05/05/06 Updating to new ActarSim (geant4.8) code
#     - 22/11/05 Updated including CINE options
#     - 31/05/05 Macro for ACTAR simulation
#
################################################################
# Macro file for testing online jobs
################################################################
# verbosity levels and saveHistory
/control/verbose 0
/control/saveHistory
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Setting the Physics modules; valid values are here listed:
#   em: standard, lowenergy, penelope, (choose one from this three)
#   common: decay,
#   hadronic: elastic, binary, binary_ion, gamma_nuc,
#   ion low-energy: ion-LowE, ion-LowE-ziegler1977, ion-LowE-ziegler1985,
#   ion-LowE-ziegler2000, ion-standard
#
#/ActarSim/phys/addPhysics local
#/ActarSim/phys/addPhysics standard
#/ActarSim/phys/addPhysics standardGS
#/ActarSim/phys/addPhysics standardSS
#/ActarSim/phys/addPhysics standardWVI
#/ActarSim/phys/addPhysics decay
#/ActarSim/phys/addPhysics elastic
#/ActarSim/phys/addPhysics binary
#/ActarSim/phys/addPhysics binary_ion
#/ActarSim/phys/addPhysics gamma_nuc
#/ActarSim/phys/addPhysics lowenergy
#/ActarSim/phys/addPhysics ion-LowE
#/ActarSim/phys/addPhysics ion-LowE-ziegler1977
#/ActarSim/phys/addPhysics ion-LowE-ziegler1985
#/ActarSim/phys/addPhysics ion-LowE-ziegler2000
#/ActarSim/phys/addPhysics ion-standard
#/ActarSim/phys/addPhysics penelope
/ActarSim/phys/addPhysics emstandard_opt0
#/ActarSim/phys/addPhysics emstandard_opt3
#/ActarSim/phys/addPhysics emstandard_opt4
/ActarSim/phys/addPhysics ionGasModels

#/process/eLoss/useCutAsFinalRange
#/process/eLoss/fluct false
#/process/eLoss/subsec
#/process/eLoss/minsubsec
#/process/eLoss/StepFunction 0.2 1. mm
#/process/eLoss/minKinEnergy 100. MeV
#/process/eLoss/maxKinEnergy 300. MeV
#/process/eLoss/verbose 1
#/process/eLoss/linLossLimit 0.5
#
# Cuts for the particles  (incomplete list, see README)
#
#  /ActarSim/phys/setGCut 0.1
#  /ActarSim/phys/setECut 0.1
#  /ActarSim/phys/setPCut 0.1
  /ActarSim/phys/setCuts 1. mm
/ActarSim/phys/verbose 0
#
# Initialization is moved here from the main allowing PhysicsList
#
/run/initialize
#
# DETECTOR CHARACTERIZATION
#
# GENERAL COMMANDS
#
# Control of the materials
/ActarSim/det/setMediumMat Galactic
#/ActarSim/det/setMediumMat Water
#Electric and Magnetic fields
#/ActarSim/det/setEleField 0 5e-3 0
#/ActarSim/det/setMagField 0 0 0 T
#
# GAS DETECTOR
#
/ActarSim/det/gasGeoIncludedFlag on
# if box
/ActarSim/det/gas/setDetectorGeometry box
/ActarSim/det/gas/setXLengthGasBox 50. mm
/ActarSim/det/gas/setYLengthGasBox 70. mm
/ActarSim/det/gas/setZLengthGasBox 50. mm
#
# if tube
#  /ActarSim/det/gas/setDetectorGeometry tube
#  /ActarSim/det/gas/setRadiusGasTub 1.0 cm
#  /ActarSim/det/gas/setLengthGasTub 1.0 cm
#
# Beam shield? tube or off
/ActarSim/det/gas/setBeamShield off
#  /ActarSim/det/gas/setBeamShield on
#  /ActarSim/det/gas/setBeamShieldMat Ion
#  /ActarSim/det/gas/setInnerRadiusBeamShieldTub 1.0 mm
#  /ActarSim/det/gas/setRadiusBeamShieldTub 1.001 mm
#  /ActarSim/det/gas/setLengthBeamShieldTub 1.0 m
#
# gas material: isoC4H10STP,  isoC4H10_150, isoC4H10_220,isoC4H10_200
#               isoC4H10_300, isoC4H10_400, isoC4H10_500, isoC4H10_710,
#               isoC4H10_1300,isoC4H10_1880
#               D2_40, D2_60, D2_80, D2_100, to D2_400 with steps of 20 mbar
#               D2_STP, D2_1695, D2_1800, D2_1950
#		D2CD4_15_500
#               He_1900, He_2010, HeCF4_300,HeCF41100, Galactic
#
/ActarSim/det/gas/setGasMat D2_STP
#
#  NOTE : Change gas also in DetectorConstruction and GasDetectorConstruction
#
# SILICON DETECTOR
#
/ActarSim/det/silGeoIncludedFlag on
#Options for Silicon and scintillator coverage:
# 6 bits to indicate which sci wall is present (1) or absent (0)
# order is:
# bit1 (lsb) beam output wall                 1
# bit2 lower (gravity based) wall             2
# bit3 upper (gravity based) wall             4
# bit4 left (from beam point of view) wall    8
# bit5 right (from beam point of view) wall   16
# bit6 (msb) beam entrance wall               32
# examples: 63 full coverage; 3 only output and bottom walls ...
/ActarSim/det/sil/sideCoverage 1
/ActarSim/det/sil/xBoxHalfLength 200. mm
/ActarSim/det/sil/yBoxHalfLength 100. mm
/ActarSim/det/sil/zBoxHalfLength 150. mm
/ActarSim/det/sil/print
#
# SCINTILLATOR DETECTOR
#
/ActarSim/det/sciGeoIncludedFlag on
# see above explanation in the equivalent command for the Silicons
/ActarSim/det/sci/sideCoverage 1
/ActarSim/det/sci/xBoxHalfLength 200. mm
/ActarSim/det/sci/yBoxHalfLength 100. mm
/ActarSim/det/sci/zBoxHalfLength 150. mm
/ActarSim/det/sci/print
#
#Control of the output on the ROOT file
#all the tracks are stored (note: huge space comsumption)
#Note: it should come before the update!!!
/ActarSim/analControl/storeTracks on
/ActarSim/analControl/storeTrackHistos on
/ActarSim/analControl/storeEvents on
/ActarSim/analControl/storeHistograms on
/ActarSim/analControl/storeSimpleTracks on
#/ActarSim/analControl/setMinStrideLength 1.
#/ActarSim/phys/stepMax 1000000.
#
# Update is mandatory after any material,field or detector change
#
/ActarSim/det/update
#/ActarSim/det/print
#
# Control of the primary events
#For all cases the possibility to have realistic beam distribution
/ActarSim/gun/beamInteraction on
/ActarSim/gun/realisticBeam off
#/ActarSim/gun/beamRadiusAtEntrance 2.5 mm
#/ActarSim/gun/emittance 200.0
#
# Realistic Event-Generator on
/ActarSim/gun/reactionFromEvGen off
#
# Reaction from Cine and Event-Generator
/ActarSim/gun/reactionFromCine off
/ActarSim/gun/reactionFromCrossSection off
#
# A) Track a particle or set of particles defined from the Particles list
#
#/ActarSim/gun/List
#/ActarSim/gun/particle proton
#if you want to use an ion, write "ion" in the previous command
#and set the Z, A and charge state in the next...
#/ActarSim/gun/ion 3 11 3
#/ActarSim/gun/energy 11. MeV
#/ActarSim/gun/direction 0 0 1
#/ActarSim/gun/time 0
#/ActarSim/gun/polarization 0
#/ActarSim/gun/number 1
/ActarSim/gun/randomVertexZPosition off
/ActarSim/gun/randomVertexZRange 0 70 mm
/ActarSim/gun/vertexZPosition 50 mm
#
# B) Track a predefined reaction from a file:
#
/ActarSim/gun/reactionFromFile off
#if you select a reaction, you should say the file in the command below
#possibilities are (up to now): He8onp_100MeV_Elastic.dat,
#He8onp_100MeV_tritium.dat, He8onC12_100MeV_Elastic.dat,
#He8onp_50MeV_Elastic.dat, He8onC12_50MeV_Elastic.dat, He8onp_50MeV_tritium.dat
#
#/ActarSim/gun/reactionFile /data/He8onp_50MeV_Elastic.dat
#/ActarSim/gun/randomReaction off    STILL NOT DONE -- ALWAYS RANDOM
#/ActarSim/gun/rowInFileReaction 4   STILL NOT DONE -- ALWAYS RANDOM
#
#
#C) Track a reacion calculated from CINE (program from W. Mittig)
#
/ActarSim/gun/reactionFromCine off
#/ActarSim/gun/Cine/incidentIon 3 8 3 0.0
#/ActarSim/gun/Cine/targetIon 2 4 2 0.0
#/ActarSim/gun/Cine/scatteredIon 3 8 3 1.0
#/ActarSim/gun/Cine/recoilIon 2 4 2 0.0
#/ActarSim/gun/Cine/reactionQ 1. MeV
#/ActarSim/gun/Cine/labEnergy 70 MeV
#/ActarSim/gun/Cine/randomTheta on
#/ActarSim/gun/Cine/thetaLabAngle 0.1
#
#D) Track a reacion calculated from KINE
#8He(12C,16C*)4He
#IMPORTANT: SINCE WE DO NOT HAVE MESSENGER FOR DECAY JUST REMEMBER TO CHANGE EXCITATION ENERGY OF MOTHER NUCLEI IN PRIMARYGENERATOR (AND ALSO GAS). FOR KINEMATICS CHECK THE FLAG AND THE MASSES OF DECAY PRODUCTS
# Record masses here 11Be:11.021657749  D:2.01410177785   10Li:10.035481259   3He:3.01602931914  9Li:9.026789 t:3.01604928 p:1.007825 n:1.008665 4He:4.00260325 12Be:12.026921 10Be:10.013533
# For Two body reaction+decay we chose CASE * (with Kine). For two body reaction we chose CASE 4 with Kine. We have to modify this at PrimaryGenerationAction until we create a messenger.
# Added realistic excitation energy for scattered particle. Modify excitation energy in PrimaryGenerationAction

/ActarSim/gun/reactionFromDecay off
/ActarSim/gun/reactionFromKine on
#/ActarSim/gun/Kine/incidentIon 6 12 6 0.0 12.00
/ActarSim/gun/Kine/incidentIon 6 13 6 0.0 13.00335483778
#/ActarSim/gun/Kine/incidentIon 2 4 2 0.0 4.00260325
/ActarSim/gun/Kine/targetIon 1 1 1 0.0 1.00782503207
#/ActarSim/gun/Kine/scatteredIon 6 12 6 0.0 12.00 
/ActarSim/gun/Kine/scatteredIon 6 13 6 0.0 13.00335483778 
#/ActarSim/gun/Kine/scatteredIon 2 4 2 0.0 4.00260325
/ActarSim/gun/Kine/recoilIon 1 1 1 0.0 1.00782503207
/ActarSim/gun/Kine/labEnergy 650 MeV
/ActarSim/gun/Kine/randomThetaCM on
#/ActarSim/gun/Kine/randomThetaRange 0.0 180.0
/ActarSim/gun/Kine/randomPhiAngle on
#/ActarSim/gun/Kine/userThetaCM 90.0 deg
#/ActarSim/gun/Kine/userPhiAngle 0. deg
#/ActarSim/gun/Kine/vertexPosition 0. 0. 7 cm
#
# VISUALIZATION
#
# Draw the whole geometry tree with details as function of verbosity
#/vis/ASCIITree/verbose 10
#/vis/drawTree
# visualization
#/vis/scene/create
#/vis/open OGLIX 600x600-0+0
#/vis/open OGLSQt 600x600-0+0
#/vis/open VRML2FILE
#/vis/viewer/set/autoRefresh 0
#/vis/viewer/flush
# set camera
#/vis/viewer/reset
#/vis/viewer/set/hiddenEdge 1
#/vis/viewer/set/lightsThetaPhi 120 40
#/vis/viewer/set/viewpointThetaPhi 115. 145.
#/vis/viewer/set/viewpointThetaPhi 90. 90.
#/vis/viewer/zoom 1.0
#/vis/viewer/set/background 1 1 1 1
#/vis/viewer/flush
#
# drawing style
#/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe
#/vis/viewer/flush
#
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set gamma red
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA e- 1 0 1 1
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA genericIon 1 0 1 1
#
# drawing the tracks
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/autoRefresh 1
#
# create an empty scene and add the detector geometry to it
#/vis/drawVolume
#/vis/scene/add/axes 0 0 0 0.1 m
#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/ActarSim/event/drawTracks all
/ActarSim/event/printModulo 1000
#
# RUN: number of events

#/run/beamOn 100000
/run/beamOn 5000