#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file vis_actar "/control/execute vis_actar.mac"
/gui/addButton g4file vis_alpha "/control/execute vis_alpha.mac"
/gui/addButton g4file vis_maiko "/control/execute vis_maiko.mac"
/gui/addButton g4file vis_kine "/control/execute vis_kine.mac"
/gui/addButton g4file vis_simpleBox "/control/execute vis_simpleBox.mac"
/gui/addButton g4file vis_simpleTube "/control/execute vis_simpleTube.mac"
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
#ACTARSim menu
#
#/gui/addMenu actarsim ACTARSim
#/gui/addButton actarsim "proton" "/ActarSim/gun/particle proton"
#/gui/addButton actarsim "alpha"  "/ActarSim/gun/particle alpha"
#/gui/addButton actarsim "ion"    "/ActarSim/gun/particle ion"
#/gui/addButton actarsim "12C"   "/ActarSim/gun/ion 6 12"

# Library menu :
/gui/addMenu lib Lib
#/gui/addButton lib "Remove libraries" "/ActarSim/phys/RemovePhysics"
/gui/addButton lib "emstandard" "/ActarSim/phys/addPhysics emstandard"
/gui/addButton lib "emstandard_opt3" "/ActarSim/phys/addPhysics emstandard_opt3"
/gui/addButton lib "emlivermore" "/ActarSim/phys/addPhysics emlivermore"
/gui/addButton lib "ionGasModels" "/ActarSim/phys/addPhysics ionGasModels"

# Run menu :
/gui/addMenu run Run
/gui/addButton run "Update" "/ActarSim/det/update"
/gui/addButton run "Initialize" "/run/initialize"
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run "beamOn 2" "/run/beamOn 2"
/gui/addButton run "Set electron cut" "/ActarSim/phys/setECut"
/gui/addButton run "Electron cut 1 mm" "/ActarSim/phys/setECut 1 mm"
/gui/addButton run "Electron cut 10 km" "/ActarSim/phys/setECut 10 km"

# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "Beam (particle)" /ActarSim/gun/particle 
/gui/addButton gun "Beam (ion)" /ActarSim/gun/ion
#/gui/addButton gun "proton" /ActarSim/gun/ion 1 1 1 0.0 1.00782503207
#/gui/addButton gun "alpha" /ActarSim/gun/ion 2 4 2 0.0 4.00260325415
#/gui/addButton gun "Carbon12" /ActarSim/gun/ion 6 12 6 0.0 12.
#/gui/addButton gun "Mg24" /ActarSim/gun/ion 12 24 12 0.0 23.985041699
#/gui/addButton gun "Fe56" /ActarSim/gun/ion 26 56 26 0.0 55.934937475
/gui/addButton gun "Energy" /ActarSim/gun/energy
#/gui/addButton gun "5 MeV" /ActarSim/gun/Kine/labEnergy 5 MeV
#/gui/addButton gun "50 MeV" /ActarSim/gun/Kine/labEnergy 50 MeV
#/gui/addButton gun "100 MeV" /ActarSim/gun/Kine/labEnergy 100 MeV
#/gui/addButton gun "RandomTheta ON"  "/ActarSim/gun/randomTheta on"
#/gui/addButton gun "RandomTheta OFF"  "/ActarSim/gun/randomTheta off"
#/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
#/gui/addButton gun "5 MeV"   "/gun/energy 1 GeV"
#/gui/addButton gun "e-"      "/gun/particle e-"
#/gui/addButton gun "pi0"     "/gun/particle pi0"
#/gui/addButton gun "pi+"     "/gun/particle pi+"
#/gui/addButton gun "neutron" "/gun/particle neutron"
#/gui/addButton gun "proton"  "/gun/particle proton"
#
# Detector menu
/gui/addMenu gas Gas
/gui/addButton gas "Pressure (bar)"  "/ActarSim/det/gas/setGasPressure"
/gui/addButton gas "Temperature (K)"  "/ActarSim/det/gas/setGasTemperature"
/gui/addButton gas "H2"  "/ActarSim/det/gas/setGasMat H2"
/gui/addButton gas "D2"  "/ActarSim/det/gas/setGasMat D2"
/gui/addButton gas "He"  "/ActarSim/det/gas/setGasMat He"
/gui/addButton gas "Ar"  "/ActarSim/det/gas/setGasMat Ar"
/gui/addButton gas "CF4"  "/ActarSim/det/gas/setGasMat CF4"
/gui/addButton gas "CH4"  "/ActarSim/det/gas/setGasMat CH4"
/gui/addButton gas "iC4H10"  "/ActarSim/det/gas/setGasMat iC4H10"
/gui/addButton gas "Number of Gases in Mixture"  "/ActarSim/det/gas/mixture/GasMixture"
/gui/addButton gas "Set Gases in Mixture"  "/ActarSim/det/gas/mixture/setGasMix"
/gui/addButton gas "Set Gas Mixture"  "/ActarSim/det/gas/setGasMat GasMix"
#
# Vis menu :
#/gui/addMenu vis Vis
#/gui/addButton vis DAWNFILE  "/control/execute visTutor/exN03Vis0.mac"
#/gui/addButton vis OpenInventor "/control/execute visTutor/exN03Vis5.mac"
#/gui/addButton vis TimeSlicing "/control/execute visTutor/exN03Vis12.mac"
#/gui/addButton vis EmShower "/control/execute visTutor/exN03Vis13.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
