################################################################
#*-- AUTHOR : Hector Alvarez-Pol
#*-- Date: 05/2005
#*-- Last Update: 15/05/08
#*-- Copyright: GENP (Univ. Santiago de Compostela)
# --------------------------------------------------------------
# Comments:
#     - 15/05/08 Multidetector geometry
#     - 05/05/06 Updating to new ActarSim (geant4.8) code
#     - 22/11/05 Updated including CINE options
#     - 31/05/05 Macro for ACTAR simulation
#
################################################################
# Macro file for testing online jobs
################################################################
# verbosity levels and saveHistory
/control/verbose 1
/control/saveHistory
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# Setting the Physics modules; valid values are here listed:
#   em: standard, lowenergy, penelope, (choose one from this three)
#   common: decay,
#   hadronic: elastic, binary, binary_ion, gamma_nuc,
#   ion low-energy: ion-LowE, ion-LowE-ziegler1977, ion-LowE-ziegler1985,
#   ion-LowE-ziegler2000, ion-standard
#
#/ActarSim/phys/addPhysics standard
#/ActarSim/phys/addPhysics decay
#/ActarSim/phys/addPhysics elastic
#/ActarSim/phys/addPhysics binary
#/ActarSim/phys/addPhysics binary_ion
#/ActarSim/phys/addPhysics gamma_nuc
#/ActarSim/phys/addPhysics lowenergy
#/ActarSim/phys/addPhysics ion-LowE
#/ActarSim/phys/addPhysics ion-LowE-ziegler1977
#/ActarSim/phys/addPhysics ion-LowE-ziegler1985
#/ActarSim/phys/addPhysics ion-LowE-ziegler2000
#/ActarSim/phys/addPhysics ion-standard
#/ActarSim/phys/addPhysics penelope
#/ActarSim/phys/addPhysics emstandard_opt0
/ActarSim/phys/addPhysics emstandard_opt3
#/ActarSim/phys/addPhysics emstandard_opt4
#/ActarSim/phys/addPhysics ionGasModels
#
#
#
# Cuts for the particles  (incomplete list, see README)
#
#  /ActarSim/phys/setGCut 0.1
#  /ActarSim/phys/setECut 0.1
#  /ActarSim/phys/setPCut 0.1
#  /ActarSim/phys/setCuts 1 mm
/ActarSim/phys/verbose 0
#
# Initialization is moved here from the main allowing PhysicsList
#
/run/initialize
#
# DETECTOR CHARACTERIZATION
#
# GENERAL COMMANDS
#
# Control of the materials
#/ActarSim/det/setMediumMat D2_STP
#/ActarSim/det/setMediumMat Galactic
#/ActarSim/det/setMediumMat Water
#Electric and Magnetic fields
#/ActarSim/det/setEleField 0 5e-3 0
#/ActarSim/det/setMagField 0 0 0 T
#
#
# gas material: isoC4H10STP, D2_STP, H2_STP
#
/ActarSim/det/gas/setGasMat D2_STP
#
# GAS DETECTOR
#
/ActarSim/det/gasGeoIncludedFlag on
# if box
/ActarSim/det/gas/setDetectorGeometry box
#
/ActarSim/det/gas/setXLengthGasBox 37. mm
/ActarSim/det/gas/setYLengthGasBox 80.9 mm
/ActarSim/det/gas/setZLengthGasBox 69. mm
#
/ActarSim/det/gas/setYGasBoxPos 12.47 mm
#
# Beam shield? tube or off
/ActarSim/det/gas/setBeamShield off
#
# SILICON DETECTOR
#
/ActarSim/det/silGeoIncludedFlag on
#Options for Silicon and scintillator coverage:
# 6 bits to indicate which sci wall is present (1) or absent (0)
# order is:
# bit1 (lsb) beam output wall                 1
# bit2 lower (gravity based) wall             2
# bit3 upper (gravity based) wall             4
# bit4 left (from beam point of view) wall    8
# bit5 right (from beam point of view) wall   16
# bit6 (msb) beam entrance wall               32
# examples: 63 full coverage; 3 only output and bottom walls ...
/ActarSim/det/sil/sideCoverage 25
/ActarSim/det/sil/xBoxHalfLength 95. mm
/ActarSim/det/sil/yBoxHalfLength 105. mm
/ActarSim/det/sil/zBoxHalfLength 120. mm
#
/ActarSim/det/sil/print
#
# SCINTILLATOR DETECTOR
#
/ActarSim/det/sciGeoIncludedFlag off
# see above explanation in the equivalent command for the Silicons
#/ActarSim/det/sci/sideCoverage 25
#/ActarSim/det/sci/xBoxHalfLength 150. mm
#/ActarSim/det/sci/yBoxHalfLength 150. mm
#/ActarSim/det/sci/zBoxHalfLength 150. mm
#
#/ActarSim/det/sci/print
#
#Control of the output on the ROOT file
#all the tracks are stored (note: huge space comsumption)
#Note: it should come before the update!!!
/ActarSim/analControl/storeTracks off
/ActarSim/analControl/storeTrackHistos off
/ActarSim/analControl/storeEvents off
/ActarSim/analControl/storeHistograms off
/ActarSim/analControl/storeSimpleTracks off
#/ActarSim/analControl/setMinStrideLength 0.1
#/ActarSim/phys/stepMax 1000000.
#
# Update is mandatory after any material,field or detector change
#
/ActarSim/det/update
#/ActarSim/det/print
#
# Control of the primary events
#For all cases the possibility to have realistic beam distribution
/ActarSim/gun/beamInteraction on
/ActarSim/gun/realisticBeam off
#/ActarSim/gun/beamRadiusAtEntrance 1.5 mm
#/ActarSim/gun/emittance 200.0
#
# Realistic Event-Generator on
/ActarSim/gun/reactionFromEvGen off
#
# Reaction from Cine and Event-Generator
/ActarSim/gun/reactionFromCine off
/ActarSim/gun/reactionFromCrossSection off
#
# A) Track a particle or set of particles defined from the Particles list
#
#/ActarSim/gun/List
#/ActarSim/gun/particle proton
#if you want to use an ion, write "ion" in the previous command
#and set the Z, A and charge state in the next...

#/ActarSim/gun/ion 1 1 1 0.0 1.00782503207
#/ActarSim/gun/ion 2 4 2 0.0 4.00260325415
#/ActarSim/gun/ion 6 12 6 0.0 12.
#/ActarSim/gun/ion 12 24 12 0.0 23.985041699
#/ActarSim/gun/ion 26 56 26 0.0 55.934937475

#/ActarSim/gun/ion 6 13 6 0.0 13.00335483778 
#/ActarSim/gun/ion 3 11 3

#/ActarSim/gun/Kine/labEnergy 4 MeV
#/ActarSim/gun/Kine/labEnergy 280 MeV
#/ActarSim/gun/energy 11. MeV
#/ActarSim/gun/position 0 0 -56 mm
#/ActarSim/gun/direction 0 0 1
#/ActarSim/gun/time 0
#/ActarSim/gun/polarization 0
#/ActarSim/gun/number 1
/ActarSim/gun/randomVertexZPosition off
#/ActarSim/gun/randomVertexZRange 50 200 mm
/ActarSim/gun/vertexZPosition 69 mm
#
# B) Track a predefined reaction from a file:
#
/ActarSim/gun/reactionFromFile off
#if you select a reaction, you should say the file in the command below
#possibilities are (up to now): He8onp_100MeV_Elastic.dat,
#He8onp_100MeV_tritium.dat, He8onC12_100MeV_Elastic.dat,
#He8onp_50MeV_Elastic.dat, He8onC12_50MeV_Elastic.dat, He8onp_50MeV_tritium.dat
#
#/ActarSim/gun/reactionFile /data/He8onp_50MeV_Elastic.dat
#/ActarSim/gun/randomReaction off    STILL NOT DONE -- ALWAYS RANDOM
#/ActarSim/gun/rowInFileReaction 4   STILL NOT DONE -- ALWAYS RANDOM
#
#
#C) Track a reacion calculated from CINE (program from W. Mittig)
#
/ActarSim/gun/reactionFromCine off
#/ActarSim/gun/Cine/incidentIon 28 78 28 0.0
#/ActarSim/gun/Cine/targetIon 1 2 1 0.0
#/ActarSim/gun/Cine/scatteredIon 28 79 28 0.
#/ActarSim/gun/Cine/recoilIon 1 1 1 0.0 
#/ActarSim/gun/Cine/reactionQ -1.5 MeV
#/ActarSim/gun/Cine/labEnergy 624 MeV
#/ActarSim/gun/Cine/randomTheta off
#/ActarSim/gun/Cine/thetaLabAngle 0.5

#D) Track a reacion calculated from KINE
#
/ActarSim/gun/reactionFromKine on
#
#/ActarSim/gun/Kine/incidentIon 1 2 1 0.0 2.0141
#/ActarSim/gun/Kine/incidentIon 2 4 2 0.0 4.001506179125
#/ActarSim/gun/Kine/incidentIon 2 4 2 0.0 4.00260325
/ActarSim/gun/Kine/incidentIon 6 13 6 0.0 13.00335483778
#/ActarSim/gun/Kine/incidentIon 50 132 50 0.0 131.9178

/ActarSim/gun/Kine/targetIon 1 1 1 0.0 1.00782503207
#/ActarSim/gun/Kine/targetIon 1 2 1 0.0 2.0141

#/ActarSim/gun/Kine/scatteredIon 1 2 1 0.0 2.0141
#/ActarSim/gun/Kine/scatteredIon 2 4 2 0.0 4.001506179125
#/ActarSim/gun/Kine/scatteredIon 2 4 2 0.0 4.00260325 
/ActarSim/gun/Kine/scatteredIon 6 13 6 0.0 13.00335483778 
#/ActarSim/gun/Kine/scatteredIon 50 133 50 0.854 132.9238

/ActarSim/gun/Kine/recoilIon 1 1 1 0.0 1.00782503207

/ActarSim/gun/Kine/labEnergy 650 MeV
/ActarSim/gun/Kine/randomThetaCM on
/ActarSim/gun/Kine/randomThetaRange 0.0 180.0
/ActarSim/gun/Kine/randomPhiAngle on
#/ActarSim/gun/Kine/userThetaCM 100.0 deg
#/ActarSim/gun/Kine/userPhiAngle 0. deg
#/ActarSim/gun/Kine/vertexPosition 0. 0. 15 cm
#
# VISUALIZATION
#
# Draw the whole geometry tree with details as function of verbosity
#/vis/ASCIITree/verbose 10
#/vis/drawTree
# visualization
/vis/scene/create
/vis/open OGLSQt
/vis/viewer/set/autoRefresh 0
/vis/viewer/flush
# set camera
/vis/viewer/reset
/vis/viewer/set/hiddenEdge 0
#/vis/viewer/set/lightsThetaPhi 120 40
/vis/viewer/set/viewpointThetaPhi 115. 145.
#/vis/viewer/set/viewpointThetaPhi 90. 90.
/vis/viewer/zoom 1.0
#/vis/viewer/set/background 1 1 1 1
/vis/viewer/flush
#
# drawing style
#/vis/viewer/set/style surface
/vis/viewer/set/style wireframe
/vis/viewer/flush
#
# drawing the tracks
#/tracking/storeTrajectory 10
/vis/scene/endOfEventAction accumulate
#/vis/scene/endOfEventAction refresh
#/vis/viewer/set/autoRefresh 1
#
# create an empty scene and add the detector geometry to it
#/vis/drawVolume
#/vis/scene/add/axes 0 0 0 0.1 m
/vis/scene/add/trajectories 
/vis/scene/add/hits
#/ActarSim/event/drawTracks all
/ActarSim/event/printModulo 10
#
# RUN: number of events
#
#/run/beamOn 100
