/********************************************************************
* ActarSimDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ActarSimDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableActarSimDict();
extern void G__cpp_setup_inheritanceActarSimDict();
extern void G__cpp_setup_typetableActarSimDict();
extern void G__cpp_setup_memvarActarSimDict();
extern void G__cpp_setup_globalActarSimDict();
extern void G__cpp_setup_memfuncActarSimDict();
extern void G__cpp_setup_funcActarSimDict();
extern void G__set_cpp_environmentActarSimDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ActarSimData.hh"
#include "ActarSimTrack.hh"
#include "ActarSimSimpleTrack.hh"
#include "ActarSimSciHit.hh"
#include "ActarSimSilHit.hh"
#include "ActarSimParisHit.hh"
#include "ActarSimPrimaryInfo.hh"
#include "ActarSimBeamInfo.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ActarSimDictLN_TClass;
extern G__linked_taginfo G__ActarSimDictLN_TBuffer;
extern G__linked_taginfo G__ActarSimDictLN_TMemberInspector;
extern G__linked_taginfo G__ActarSimDictLN_TObject;
extern G__linked_taginfo G__ActarSimDictLN_TString;
extern G__linked_taginfo G__ActarSimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ActarSimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ActarSimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ActarSimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ActarSimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimData;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimTrack;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimSimpleTrack;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimSciHit;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimSilHit;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimParisHit;
extern G__linked_taginfo G__ActarSimDictLN_G4PrimaryParticle;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimPrimaryInfo;
extern G__linked_taginfo G__ActarSimDictLN_ActarSimBeamInfo;

/* STUB derived class for protected member access */
